delete_sms:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: huawei_lte_extended
    index:
      required: true
      selector:
        number:
          min: 0
          mode: box

get_sms_list:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: huawei_lte_extended
    page:
      default: 1
      selector:
        number:
          min: 1
          max: 100
          mode: box
    count:
      default: 20
      selector:
        number:
          min: 1
          max: 50
          mode: box

mark_read:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: huawei_lte_extended
    index:
      required: true
      selector:
        number:
          min: 0
          mode: box

send_sms:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: huawei_lte_extended
    phone:
      required: true
      selector:
        text:
    message:
      required: true
      selector:
        text:
          multiline: true
